version: "3.9"
services:
  api:
    services:
  extractor-api:
    build:
      context: .
      target: prod
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - extractor-net
    
networks:
  extractor-net:
    driver: bridge