services:
  - type: web
    name: extractor-facturas
    env: python
    region: oregon
    plan: free

    buildCommand: |
      pip install --no-cache-dir -r requirements.txt

    startCommand: |
      apt-get update && apt-get install -y \
        tesseract-ocr \
        tesseract-ocr-spa \
        libtesseract-dev \
        poppler-utils \
        && rm -rf /var/lib/apt/lists/* && \
      uvicorn server:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: PYTHON_VERSION
        value: 3.13